config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'groups#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources   :users,  only: [:index, :edit, :update]
  resources   :groups, only: [:new, :update, :edit, :create] do
    # new画面を必要としないため、createのみでよい。
    resources :messages, only: [:create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages
  def show_last_message
    if (last_message = messages.last).present?
      if last_message.message?
       last_message.message
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  # 画像だけの送信を可能にするために、バリデーションの条件にimageがからである事を入れている。
  mount_uploader :image, ImageUploader
  validates :message, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :groups, through: :members
  has_many :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

   protected
     def configure_permitted_parameters
       #以下の:name部分は追加したカラム名に変える
       devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
     end
     def after_sign_out_path_for(resouce)
        new_user_session_path
     end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end
  def create
    @group = Group.create(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました。'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end
  private

  def group_params
    params.require(:group).permit(:group_name, { :user_ids => [] })
  end
  def set_group
      @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    #@group = Group.find(params[:group_id])before_actionで処理
    @messages = @group.messages.includes(:user)
    @users    = @group.users.map{|user| user.user_name}
    @message  = Message.new
    respond_to do |format|
      format.html
      format.json
    end
  end
  def create
      @message = @group.messages.new(message_params)
        #validationがあるのでsaveしたタイミングで、nilは除外してくれる
      if @message.save
        respond_to do |format|
          format.html { redirect_to group_messages_path( @group ) , notice: "投稿されました" }
          format.json
        end
      else
        @messages = @group.messages.includes( :user )
        flash.now[:alert] = "メッセージを入力してください。"
        # renderは、コントローラのindexに行くのではなくviewに行く。
        render :index
      end
  end
  private
  def message_params
    params.require(:message).permit(:message, :image).merge(user_id: current_user.id)
  end
  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # ここで本来ならばグループメンバーを弾くべきだが、editとnewが共存する_form.html.hamlでの実現方法がわからない。。。
    @users     = User.where('user_name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update( user_params )
      redirect_to root_path , notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:user_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_chat_user.html.haml
- group.users.each do |user|
  #chat-group-user-8.chat-group-user.clearfix.js-chat-member
    %input{:name => "group[user_ids][]", :type => "hidden", :value => "#{user.id}"}/
    %p.chat-group-user__name
      = user.user_name
    %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除

app/views/groups/_form.html.haml
= form_for group, html: {id: 'new_chat_group', class: 'new_chat_group'} do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_message.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_message.each do |message|
          %li = message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label 'グループ名',for: 'chat_group_name', class: 'chat-group-form__label'
    .chat-group-form__field--right
      =f.text_field :group_name, id: 'chat_group_name', class: 'chat-group-form__input', placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right#user-membe-result
      = render 'chat_user', { group: group }
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn', disable_with: "Save", name: "commit", value: "Save"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form', { group: @group }

app/views/groups/index.html.haml
.container
  =render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag :div, value, class: "flash flash__#{key}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      = render "layouts/flash"
    = yield

app/views/messages/_main__contents__message.html.haml
.container__main__contents__message
  .container__main__contents__message__dammyheader
  .container__main__contents__message__header
    %h2
      = message.user.user_name
    %span
      = message.created_at
  .container__main__contents__message__text
    %p
      = message.message
  .container__main__contents__message__image
    = image_tag message.image.to_s

app/views/messages/_message.html.haml
.container__main__contents__message
  .container__main__contents__message__dammyheader
  .container__main__contents__message__header
    %h2
      = message.user.user_name
    %span
      = message.created_at
  .container__main__contents__message__text
    %p
      = message.message
  .container__main__contents__message__image
    = image_tag message.image.to_s

app/views/messages/index.html.haml
.container
  = render 'shared/side_bar'
  .container__main
    .container__main__header
      .container__main__header__left
        %h2
          = @group.group_name
        %p
          ="Menber:#{@users.join(", ")}"
      .container__main__header__right
        =link_to "Edit", "/groups/#{params[:group_id]}/edit", :class => "container__main__header__right__edit"
    .container__main__contents
      = render @messages
    .container__main__footer
      = form_for [@group, @message] , html: {id: 'new_message'} do |f|
        .container__main__footer__left
          = f.text_field :message, class: "container__main__footer__left__send", placeholder: "type a message"
          %label.upload-label{ for: "uploader-icon" }
            %span.picture
              %i.fa.fa-picture-o
              = f.file_field :image, id: "uploader-icon"
        .container__main__footer__right
          = f.submit "send", class: "container__main__footer__right__submit"

app/views/shared/_side_bar.html.haml
.container__sidebar
  .container__sidebar__header
    %h3
      = current_user.user_name
    = link_to edit_user_path( current_user ) do
      %span.post__image
        %i.fa.fa-cog
    =link_to new_group_path( current_user ) do
      %span.settings
        %i.fa.fa-edit
  .container__sidebar__contents
    - current_user.groups.each do |group|
      .container__sidebar__contents__group
        =link_to "",group_messages_path( group )
        .container__sidebar__contents__group__title
          %h4
            = group.group_name
        .container__sidebar__contents__group__message
          %p
            = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2#edit--border Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :user_name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'